#!/bin/bash

for i in {1..50}; do
#iki directory
  namadir="Directory$i"
  mkdir -p "$namadir"
for a in {1..50}; do
#iki file e
  filename="$namadir/file$a.txt"
  echo -e "Hallo saya adalah file ke$a\nSaya dibuat pada:$(date)" > "$filename"
  echo "OKE!! $filename telah dibuat"
done
done
